### ISSUE TITLE
batch & multihead support?

### ISSUE THREAD

**Issue by GallagherCommaJack** [lucidrains/flash-attention-jax#4]
how hard would it be to add in support for leading dimensions (for e.g. batching & multiple heads)?
in my experience `vmap` is often less performant than batching by hand.

**Comment by GallagherCommaJack** [comment]
I haven't benchmarked your `plain_attention` against a hand-batched approach yet, but did see some very strange performance characteristics (eg getting faster when I wrapped with `jax.value_and_grad`!)

**Comment by lucidrains** [comment]
@GallagherCommaJack hey Jack

are you using this for text to image? i threw in a commit this morning that will support batch and heads, but only for non-causal https://github.com/lucidrains/flash-attention-jax/commit/874af93e87e35b29dff5207a927c875229630502

**Comment by GallagherCommaJack** [comment]
yep! non-causal should be totally sufficient here :)
